### ISSUE TITLE
libupnp crashes with musl 1.1.20+

### ISSUE THREAD

**Issue by diizzyy** [mrjimenez/pupnp#102]
Hi,
I've been tracking down this issue for a while now and it seems like it originates from libupnp and undefined behaviour using pthreads.

https://github.com/openwrt/packages/issues/7473#issuecomment-453838290 (backtrace)
I've also tried with the latest version of musl, libupnp (1.6.25 and 1.8.4), libupnpp and upmpdcli with the same result.

https://opensourceprojects.eu/p/upmpdcli/tickets/37/

**Comment by medoc92** [comment]
Hi, 

I think that the problem is that libupnp is calling pthread_detach() on a thread which was created in the detached state (and not pthread_join()). In ThreadPool.c around line 648:

~~~~
	ithread_attr_init(&attr);
	ithread_attr_setstacksize(&attr, tp->attr.stackSize);
	ithread_attr_setdetachstate(&attr, ITHREAD_CREATE_DETACHED);
	rc = ithread_create(&temp, &attr, WorkerThread, tp);
	ithread_attr_destroy(&attr);
	if (rc == 0) {
		rc = ithread_detach(temp);
		/* ithread_detach will return EINVAL if thread has been
		 successfully detached by ithread_create */
		if (rc == EINVAL)
			rc = 0;
~~~~

I don't see the point of the supplementary ithread_detach() (if there is one they should have added a comment :) )

According to the man page:
~~~~
       Attempting to detach an already detached thread results in unspecified behavior.
~~~~

So I think that it would be reasonable to just get rid of the ithread_detach() call and the following lines.
