### ISSUE TITLE
Sourceforge vs. GitHub

### ISSUE THREAD

**Issue by grahamc** [mrjimenez/pupnp#14]
Hi,

GitHub says 1.6.21 is the latest release: http://pupnp.sourceforge.net/ but no file is available for that release.

Has pupnp development officially moved here? Could you put a link from the SF project page saying the project can also be found here?

As a packager for NixOS, this would make my life easier.

Thank you,
Graham

**Comment by grahamc** [comment]
Note: I see that 1.6.21 matches sourceforge, but an official statement on the SF page would be very useful.

**Comment by grahamc** [comment]
Final update: I see now Features on the page references here. It would be helpful though to have a bigger notice on the webpage :)

Thank you!

**Comment by v00d00** [comment]
I feel like making github the main repository and archiving the SF one would be a really good idea. Its so much nicer to use than SF and it makes contributions really easy, @mrjimenez thoughts?

**Comment by grahamc** [comment]
FWIW:

 - I don't mind official development being over at SF
 - but I want clarify that this is officially related
 - and I'd like continuity in where to get releases

**Comment by ffontaine** [comment]
I think Marcello encountered an issue when updating the SF website (see #12):
> Ok, just updated the repos, will put the tar on the site right now.

Personnally, I think we should indeed clearly state on the sourceforge website that github is now the official repo. @mrjimenez, do you agree on this proposal?

**Comment by mrjimenez** [comment]
Hi Folks,

Since we moved from svn to git development some years ago, it seems to me it is not relevant what the "official" site is.  Distributed version control systems make it difficult to define "official" in this context. The official site will be where we have more contributions, I see GitHub much more adequate than SF in that respect due to the "merge request" facilities. But I have nothing against good old text file patches as long as they have been generated with "git format-patch". I could even accept "patch" generated files, but that seems rather pointless nowadays, not to mention that it makes the maintainers lives a little harder.

I currently use both SF and GitHub. Do you folks have a strong reason for why there should be an "official" site? Currently, what is the difference between downloading a tar from SF or GitHub? I am open to your ideas.

I keep the repos in SF updated for historical reasons, the original UPnP library was hosted in SF since 2000, this library is a fork and has been hosted in SD since 2006 (ten years!). For 16 years everybody has been downloading and using the bug tracking facilities from SF. Keeping the repos in sync is no burden for me, since I have been doing this for quite a long time and all it takes is running a script. So I usually do this on a changeset/bug report basis.

Please excuse me for the delay in posting the tar balls on the SF site, all my fault. What actually happened was that I have been interrupted when I was about to upload the SF files and then forgot to finish it later. Thanks for pointing it out!

Regards,
Marcelo.

**Comment by grahamc** [comment]
Marcelo Roberto Jimenez <notifications@github.com> writes:

> I currently use both SF and GitHub. Do you folks have a strong reason
> for why there should be an "official" site? Currently, what is the
> difference between downloading a tar from SF or GitHub? I am open to
> your ideas. 

Thank you for getting back to me! My main want is for an official notice
saying this is also a valid place to get the source. The reason I want
a notice of that  is because there is trust that _you_ are developing
good code, and to be sure there is a link from old to new. This way, we
can be fairly confident it isn't just a mrjimenez impersonating you.

Of course, I did see already you link to it in the Features page. It
took a lot of sleuthing to find that, though.

Thank you,
Graham

**Comment by mrjimenez** [comment]
Hi Graham,

I have just added a line in the SF description that points to GitHub. Would that be enough?

As for "developing good code", please notice that what we do most is maintain, not develop. I myself have some concerns about the quality of the code, I did some big changes in the past, but certainly have not addressed all quality problems. Currently and unfortunately, I have very limited time resources to dedicate to this project.

Thank you for your considerations!
Regards,
Marcelo.

**Comment by grahamc** [comment]
Marcelo Roberto Jimenez <notifications@github.com> writes:


> I have just added a line in the SF description that points to GitHub.
> Would that be enough? 

That is enough :) thank you.

> As for "developing good code", please notice that what we do most is
> maintain, not develop.

That is what I mean, yes.
