### ISSUE TITLE
New 1.8.1 release?

### ISSUE THREAD

**Issue by v00d00** [mrjimenez/pupnp#34]
Hi,

Please make a new release of the changes since 1.8. I am especially interested in the SO_READDR stuff being available in a released version.

Thanks!

**Comment by mrjimenez** [comment]
Hi Ian,

Let me just finish the two pending pull requests and we can do that.

Regards.

**Comment by v00d00** [comment]
Ok great, looks like you are getting through them.

**Comment by v00d00** [comment]
Any update?

**Comment by mrjimenez** [comment]
Hi Ian,

I am ok with a new release, I am just too overwhelmed with work to stop and do it now.

Any volunteer?

Regards,
Marcelo.

**Comment by v00d00** [comment]
Perhaps @ffontaine could take a look? I could do it if you tell me steps! 👍 Though I wont have access for SF etc.

Perhaps switch the release to be a simple github "release" it may be easier to releases in future, 1.8 is already done this way.

**Comment by mrjimenez** [comment]
It can be done either place. I suppose you prefer to do it in github, I am fine with it, I can echo it to SF and create the tar.bz2 file, no problem.

Generating a new release is done by creating two commits. The first one updates the library numbers in the file configure.ac. This is a little tricky because of libtool numbering scheeme, but the instructions are in the same file. This is the "time consuming" part, because you should look at every commit since the last release to see if there is a change in code or interface. This commit is usually called "Adjust the library numbers for release" and it receives the tag with the library number like "release-1.8.2".

The second commit is usually called "Homekeeping for the next release" and adjusts some library numbers spread all over the project.

What I usually do is to check for the last release tag in gitk to see the diff, so that I can do something similar every time.

If you decide to do it, it will be great!

Best regards,
Marcelo.

**Comment by ffontaine** [comment]
Hello, I made PR #39. Code has changed in ixml (b87c294edced7966fc0959dc6e329a1189f04bda) and as threadutil has been merged in upnp, we can consider that a new interface has been added to upnp.

**Comment by ffontaine** [comment]
Release 1.8.1 is out. @v00d00, if it's ok for you, you can close this issue.

**Comment by v00d00** [comment]
@ffontaine, Great, thanks!

(Can you take a look at #37 also :+1: )

**Comment by ffontaine** [comment]
Yes, I will look at it.
