### ISSUE TITLE
Apply @medoc92's patches from sourceforge

### ISSUE THREAD

**Issue by v00d00** [mrjimenez/pupnp#43]
Hi,

Please consider merging the below patches, written by @medoc92 and submitted to sourceforge a while ago.

The patches are:

https://github.com/medoc92/pupnp16/commit/90d8a5b3ebf59c69f5d0ffb97c0abc0f981c2ef6 (Reorganise genaInitNotifyExt and genaNotifyAll/genaNotifyAllExt)

https://github.com/medoc92/pupnp16/commit/885c51ba77ba251b024d1d4298c55635d59f1905 ( Queue events on their subscription object instead of adding them to the thread pool immediately.)

I think this will help with too many jobs and https://github.com/v00d00/gerbera/issues/96

and 

https://github.com/medoc92/pupnp16/commit/44dfe018d95b4043f8be272e59c82b18b48bdea2 (ChangeLog for the above changes)

The first two apply cleanly to master.

Thanks!

**Comment by mrjimenez** [comment]
Done!

**Comment by v00d00** [comment]
Great thanks, and thanks to @medoc92 for the patches.

**Comment by medoc92** [comment]
Ian Whyman writes:
 > Great thanks, and thanks to @medoc92 for the patches.


Thanks to Marcelo for applying the patches.

What would be really great would be to have them in branch 1.6 too.

I have been maintaining a fork of libupnp 1.6, and deb packages, just
for this reason for the last few years.

As far as I know, the packages for the patched 1.6 ship with every
audio-oriented distribution for the Raspberry Pi (I just checked again for
Volumio, and I think that the others do the same), so they've probably been
tested all right... Volumio 2 alone claims 900k+ downloads.

Cheers,

jf

**Comment by v00d00** [comment]
@medoc92 I'm not certain if you have any other patches outstanding, but it would be great to get these merged too.

**Comment by medoc92** [comment]
Ian Whyman writes:
 > @medoc92 I'm not certain if you have any other patches outstanding, but it
 > would be great to get these merged too.

The patch about event queuing is the only one with consequences on library
function.

There are probably a few other changes in the forked code, but they are
mostly about building from source, nothing important.

I'd need to have a good look at a full diff between the forked and standard
code one day, to see what has been independantly fixed, but it's a lot of
work and only makes sense before dropping the fork, which can only happen
after the event queuing issue is merged. For now, I just apply the standard
1.6 branch commits as they come.

jf

**Comment by ffontaine** [comment]
I didn't have time to review all the modifications made in these patches. However, here is a first set of comments:
 - UPNP_ENABLE_NOTIFICATION_REORDERING has been removed and is not used anymore in the code so we should remove it from configure.ac.
 - The job that is allocated in genaNotifyAllCommon is never freed
 - It seems that we're now discarding GENA notifications to unresponding Control Points if we have more than MAX_SUBSCRIPTION_QUEUED_EVENTS (5 by default). First, the default value seems very low and second this is not compliant with UPnP UDA .1.0 (http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.0.pdf):

> **If there is no response from a subscriber to any event message, the publisher should continue to attempt to send subsequent event messages to the subscriber until the subscription expires.** 
[...]
To acknowledge receipt of this event message, a subscriber must respond within 30 seconds, including expected transmission time. **If a subscriber does not respond within 30 seconds,** or if the publisher is unable to connect to the subscription URL, **the publisher should abandon sending this message to the subscriber but should keep the subscription active and send future event messages** to the subscriber until the subscription expires or is cancelled.

The UDA 1.0 specifies that this a should and not a must so it will probably be ok for the certification test tool.

As a conclusion, I think that is a nice but heavy change in the way GENA notifications are handled. For example, if a control point subscribes for 30 minutes and encounters some connectivity issues due to a poor network quality, it will "quickly" loose events. We should definitely give more information to your users in the ChangeLog especially about the new MAX_SUBSCRIPTION_QUEUED_EVENTS.

**Comment by medoc92** [comment]
Fabrice Fontaine writes:
 > I didn't have time to review all the modifications made in these patches.
 > However, here is a first set of comments:
 > 
 >   • UPNP_ENABLE_NOTIFICATION_REORDERING has been removed and is not used
 >     anymore in the code so we should remove it from configure.ac.
 >   • The job that is allocated in genaNotifyAllCommon is never freed
 >   • It seems that we're now discarding GENA notifications to unresponding
 >     Control Points if we have more than MAX_SUBSCRIPTION_QUEUED_EVENTS (5 by
 >     default). First, the default value seems very low and second this is not
 >     compliant with UPnP UDA .1.0 (http://upnp.org/specs/arch/
 >     UPnP-arch-DeviceArchitecture-v1.0.pdf):
 > 
 >     If there is no response from a subscriber to any event message, the
 >     publisher should continue to attempt to send subsequent event messages to
 >     the subscriber until the subscription expires.
 >     [...]
 >     To acknowledge receipt of this event message, a subscriber must respond
 >     within 30 seconds, including expected transmission time. If a subscriber
 >     does not respond within 30 seconds, or if the publisher is unable to
 >     connect to the subscription URL, the publisher should abandon sending this
 >     message to the subscriber but should keep the subscription active and send
 >     future event messages to the subscriber until the subscription expires or
 >     is cancelled.
 > 
 > The UDA 1.0 specifies that this a should and not a must so it will probably be
 > ok for the certification test tool.
 > 
 > As a conclusion, I think that is a nice but heavy change in the way GENA
 > notifications are handled. For example, if a control point subscribes for 30
 > minutes and encounters some connectivity issues due to a poor network quality,
 > it will "quickly" loose events. We should definitely give more information to
 > your users in the ChangeLog especially about the new
 > MAX_SUBSCRIPTION_QUEUED_EVENTS.


The point of the change is that queued events for a non-responding CP only
consume memory instead of flooding the thread pool until nothing can be
done any more and the device becomes unresponsive.

The goal is that there will be only one event thread task for any given
subscriber, because the thread pool is a limited resource, and it does not
make sense to let it DOSed by a single client.

I wrote this a number of years ago so I'm a bit hazy on the details. Could
you be a bit more specific about a job not being deleted ? I think that I
was quite careful about these issues, but I may have missed something.

The maximum number of queued events could be raised, or we can change the
order in which events are abandonned when the maximum queue size is
reached, in order to better conform to what the standard says. I do think
that it's reasonable to have a maximum queue size, but it could be 500 just
as well, or we can only delete things older than 30 S if this is the right
thing to do.

jf

**Comment by ffontaine** [comment]
Concerning the job structure, at line 815 of gena_device.c, there is a malloc:
`				job = (ThreadPoolJob *)malloc(sizeof(ThreadPoolJob));`
I think it should be freed on ExitFunction, no?

Concerning the maximum number of queued events, deleting events older than 30 seconds seems indeed the right thing to do.

**Comment by medoc92** [comment]
Fabrice Fontaine writes:
 > Concerning the job structure, at line 815 of gena_device.c, there is a
 > malloc: 
 > job = (ThreadPoolJob *)malloc(sizeof(ThreadPoolJob));
 > I think it should be freed on ExitFunction, no?

I don't think so, because it is stored in the list for the subscription. I
think that it is freed by the calls to ListDelNode() (node->item is the
job, and ListInit() is called with free() as free_function). But I'm open
to discussion, this is really old stuff :)

 > Concerning the maximum number of queued events, deleting events older
 > than 30 seconds seems indeed the right thing to do.

Ok, it would be easy to store a timestamp in the notify_thread_struct, and
only delete anything if it is older than 30S. If the standard says
so... This would really be 2-3 lines of additional code.

OTOH, I am not sure how wise it would be. Do you think that there are
clients which actually rely on the delivery of all events ? This would seem
quite unwise given that there is no sequence number (or is there?). I am
really no UPnP standard expert.

I am not sure that I can think of cases where the queue size would become a
real issue, but some devices don't have gobs of memory, and I'd be worried
if there was no queue depth limitation at all. The current version limits
the memory used by becoming totally unresponsive :).

jf

**Comment by mrjimenez** [comment]
Hi Jf,

On Fri, Jun 16, 2017 at 5:53 AM, Jean-Francois Dockes <
notifications@github.com> wrote:

>
> Thanks to Marcelo for applying the patches.
>
> What would be really great would be to have them in branch 1.6 too.
>
> I have been maintaining a fork of libupnp 1.6, and deb packages, just
> for this reason for the last few years.
>
> As far as I know, the packages for the patched 1.6 ship with every
> audio-oriented distribution for the Raspberry Pi (I just checked again for
> Volumio, and I think that the others do the same), so they've probably been
> tested all right... Volumio 2 alone claims 900k+ downloads.
>

If you prepare a changeset, or even a bunch of diffs from the latest 1.6
repo, in the case the latter be easier, I will be happy to apply them to
1.6. I was looking at your fork, and it seems like it has not been rooted
in my repo on git, so we are not able to exchange changesets (I might be
wrong on that, though). But plain old diffs will do.


>
> Cheers,
>
> jf
>

Regards,
Marcelo.

**Comment by medoc92** [comment]
Marcelo Roberto Jimenez writes:
 > Hi Jf,
 > 
 > On Fri, Jun 16, 2017 at 5:53 AM, Jean-Francois Dockes <
 > notifications@github.com> wrote:
 > 
 > >
 > > Thanks to Marcelo for applying the patches.
 > >
 > > What would be really great would be to have them in branch 1.6 too.
 > >
 > > I have been maintaining a fork of libupnp 1.6, and deb packages, just
 > > for this reason for the last few years.
 > >
 > > As far as I know, the packages for the patched 1.6 ship with every
 > > audio-oriented distribution for the Raspberry Pi (I just checked again for
 > > Volumio, and I think that the others do the same), so they've probably been
 > > tested all right... Volumio 2 alone claims 900k+ downloads.
 > >
 > 
 > If you prepare a changeset, or even a bunch of diffs from the latest 1.6
 > repo, in the case the latter be easier, I will be happy to apply them to
 > 1.6. I was looking at your fork, and it seems like it has not been rooted
 > in my repo on git, so we are not able to exchange changesets (I might be
 > wrong on that, though). But plain old diffs will do.

I think that the links between the two repositories are a mess. I tried to
rebase my commits for some time, but then it did not work any more, and
now I'm just cherry-picking the commits from your 1.6.x branch.

I checked that the original patches apply without conflicts to the current
sourceforge branch-1.6.x branch.

When I then check the diffs with the forked repo, there is nothing
significant I can see: some minor Windows build issues, some minor
changes in the upnpdebug module, some missing newlines at the end of log
messages.

And also 'configure' defaults to non-blocking tcp connections.

It could be that none of this is needed at all any more, and I'll check and
possibly submit patches before ditching the fork anyway.

I think that you could just apply the two patches:

0004-Factorized-code-common-to-genaInitNotify-genaInitNot.patch,

then

0008-Queue-events-on-their-subscription-object-instead-of.patch

But first, maybe we need to come to a conclusion about Fabrice Fontaine
remarks ? This stuff is more than 2 years old, there is no great urge :)

There is no reason why the maximum event queue length and possible age
verification need to be constants by the way. We could have compile time
defaults and an interface to change them (adding a function call to adjust
the default parameters at run time would break neither the ABI nor the API
for existing code). Something in the spirit of the existing
UpnpSetMaxContentLength(). 

Cheers,

jf

**Comment by v00d00** [comment]
Getting the patches included in official 1.6 releases would be great, less forks is always nicer.

Perhaps merge the patches, then we can adjust behaviour further with additional commits/pulls as needed?

**Comment by mrjimenez** [comment]
Hi Ian,

I agree, it will be much easier to apply the new behavior if these patches
are already in.

Indeed, the patches apply without problems, so they have been committed to
1.6.x.

Regards,
Marcelo.

**Comment by medoc92** [comment]
Marcelo Roberto Jimenez writes:
 > Hi Ian,
 > 
 > I agree, it will be much easier to apply the new behavior if these patches
 > are already in.
 > 
 > Indeed, the patches apply without problems, so they have been committed to
 > 1.6.x.
 > 
 > Regards,
 > Marcelo.

Thanks ! I'm so glad to get rid of the forked repo at last !

jf


 > On Fri, Jun 16, 2017 at 2:52 PM, Ian Whyman <notifications@github.com>
 > wrote:
 > 
 > > Getting the patches included in official 1.6 releases would be great, less
 > > forks is always nicer.
 > >
 > > Perhaps merge the patches, then we can adjust behaviour further with
 > > additional commits/pulls as needed?

**Comment by medoc92** [comment]
Fabrice Fontaine writes:
 > [...]
 >   • It seems that we're now discarding GENA notifications to unresponding
 >     Control Points if we have more than MAX_SUBSCRIPTION_QUEUED_EVENTS (5 by
 >     default). First, the default value seems very low and second this is not
 >     compliant with UPnP UDA .1.0 (http://upnp.org/specs/arch/
 >     UPnP-arch-DeviceArchitecture-v1.0.pdf):
 > 
 >     If there is no response from a subscriber to any event message, the
 >     publisher should continue to attempt to send subsequent event
 >     messages to the subscriber until the subscription expires.
 >     [...]
 >     To acknowledge receipt of this event message, a subscriber must
 >     respond within 30 seconds, including expected transmission time. If
 >     a subscriber does not respond within 30 seconds, or if the publisher
 >     is unable to connect to the subscription URL, the publisher should
 >     abandon sending this message to the subscriber but should keep the
 >     subscription active and send future event messages to the subscriber
 >     until the subscription expires or is cancelled.
 > 
 > The UDA 1.0 specifies that this a should and not a must so it will
 > probably be ok for the certification test tool.
 > 
 > As a conclusion, I think that is a nice but heavy change in the way GENA
 > notifications are handled. For example, if a control point subscribes
 > for 30 minutes and encounters some connectivity issues due to a poor
 > network quality, it will "quickly" loose events. We should definitely
 > give more information to your users in the ChangeLog especially about
 > the new MAX_SUBSCRIPTION_QUEUED_EVENTS.


The previous code made an attempt to conform to the standard but did not
work in presence of a non-responding subscriber (very ennoying incidents of
non-responding devices were frequently reported). The new code does not
even try to conform, but it works fine in practise. It may be possible to
find a compromise and I would appreciate some help.


I had another look at the standard text (and thanks to this, I am now wiser
and know that there is indeed an event sequence number... )

However I have a bit of trouble understanding the text
(UPnP-arch-DeviceArchitecture-v1.1-20081015.pdf) and I'd appreciate
explanations from someone more familiar with the accepted interpretation.

This paragraph in the beginning of section 4.3 implies that unicast event
Keys are per-subscription:

	In unicast eventing, a separate event key MUST be maintained by the
	publisher for each subscription to facilitate error detection (as
	explained below). The event key for a subscription is initialized to 0
	when the publisher sends the initial event message. For each subsequent
	event message, the publisher increments (by one) the event key for a
	subscription, and includes that updated key in the event message.

But then we have the following in section "4.3.2 Unicast eventing: Event
messages: NOTIFY":

    Event messages sent to different subscribers that have the same
    sequence number MUST contain the same content except for the HOST
    header field

It appears that the "sequence number" here is the same as the "event
key". If this is the case, the paragraphs seem to be in contradiction.
Given the repeated requirement that the first message for a subscription
must have number 0, I think that the 2nd paragraph above is an error and
should be ignored ?

If we come back to the paragraph quoted in the message:

 >     To acknowledge receipt of this event message, a subscriber must
 >     respond within 30 seconds, including expected transmission time. If
 >     a subscriber does not respond within 30 seconds, or if the publisher
 >     is unable to connect to the subscription URL, the publisher should
 >     abandon sending this message to the subscriber but should keep the
 >     subscription active and send future event messages to the subscriber
 >     until the subscription expires or is cancelled.

It would appear that the 30 S timeout is per-event and does not affect
subsequent events. This means that, for a service which generates events at
intervals shorter than 30 S, multiple event connections need to be
attempted in parallel, else the queue will grow indefinitely until the end
of the subscription. Of course "future event messages" could also be
interpreted as meaning that any event occurring in the 30 S window can be
discarded (they are not "future").

The standard does not seem to forbid explicitly the device to initiate
multiple connections to the control point to send several events at once
(this would imply that events are sometimes be sent/received out of order).

Actually, this was the one way that the previous version of the code could
be made to sort of work in this situation: disable
UPNP_ENABLE_NOTIFICATION_REORDERING (which would allow parallel connect
attempts), and disable UPNP_ENABLE_BLOCKING_TCP_CONNECTIONS (which would
then use a connect timeout of 5 S). This would limit the number of stuck
threads to something workable (with typical event rates). Note that this was
not conforming to the standard because of the 5 S value (should have been
30), and that raising the event rate would cause the problem to reappear
anyway.

To conform to the (rather unreasonable) requirements in the standard, the
software would need to support a high number of ongoing connection attempts
(there is no high limit, it depends on the event rate, but, realistically, a
few dozens to a few hundreds).

This would not be practical with the current code which uses one thread per
connect() attempt. We would have to change to a model where a single thread
can monitor multiple connecting sockets by using select() and then pass the
connected sockets() to other threads for doing the actual transfers.

This would be a significant development task, and I don't really feel up to
it.

The idea of discarding old events is not really allowed by the standard:
each event should get its 30 S in the sun (of connection attempt). However,
it would not be too bad to consider that, as long as one connection is not
succeeding, others would not either (this is not entirely true because
network paths, random dropped packets, etc. but let's pretend). It then
becomes reasonable to discard events in queue for more than 30 S behind an
ongoing connection attempt **even if no connection attempt has been
performed for them**.

So here goes my proposed solution:

We define 2 configurable parameters:

- A timeout value for dropping events, with a default of 30 S.
- The current MAX_SUBSCRIPTION_QUEUED_EVENTS, with a default which could be
  increased to maybe 10 ? This would lower the risk of dropped events, but
  should still use a reasonable amount of memory.

And we add a call to allow configuring the values at runtime (something like
upnpapi.c:UpnpSetMaxContentLength())


Configuring a very high value for MAX_SUBSCRIPTION_QUEUED_EVENTS would
allow an implementation to be close to the standard (with a cost in memory
used). We could specify that a value of 0 means no limit...

We can store the time in the notify_thread_struct structure, which is not
externally visible and always dynamically allocated (by the way, the
eventKey field in there is set but never used).

I'd be very interested by your input on the subject.

Cheers,

jf

**Comment by ffontaine** [comment]
pupnp claims to be compliant in UDA 1.0 but I think you're right. The 2nd paragraph seems to be an error in UDA 1.1. This error seems related to the multicast eventing which is one of the big addition of UDA 1.1. This paragraph is not present in UDA 1.0 (http://www.upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.0-20080424.pdf).

Concerning your proposal, it seems good to me.

Fabrice

**Comment by medoc92** [comment]
Fabrice Fontaine writes:
 > pupnp claims to be compliant in UDA 1.0 but I think you're right. The
 > 2nd paragraph seems to be an error in UDA 1.1. This error seems related
 > to the multicast eventing which is one of the big addition of UDA
 > 1.1. This paragraph is not present in UDA 1.0
 > (http://www.upnp.org/specs/arch/
 > UPnP-arch-DeviceArchitecture-v1.0-20080424.pdf).
 > 
 > Concerning your proposal, it seems good to me.
 >
 > Fabrice

Ok, I'll submit a pull request next week.

By the way, I have found an even easier way to reproduce the problem: just
suspend a subscribed Unix/Linux Control Point process... No need for fancy
network stuff.

jf
